### PR TITLE
Pull Request for the branch (mobile-menu)

### PR DESCRIPTION
**Pull request by HamzaAnwar1998**
add a popup menu that fills the entire screen when a user clicks on the hamburger icon.
add a cross icon that closes the popup menu
fixed the header
add a redirection to the specific section of the page when a user clicks on any nav link

### CODE REVIEW

**Review by ShoiraTa — CHANGES_REQUESTED** [review]
Hi Team,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Amazing UI ✔️ 
- Nice animation 👏🏻  
- The JavaScript code is implemented following the best practices  👍🏻 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [ ] This is the first project in which you should set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters in the project repository
Please open the [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) and make sure to follow all the steps in order to properly setup JS linters. 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HamzaAnwar1998** [comment]
> Hi Team,
> 
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 
> **First let me to point out:**
> 
> * Amazing UI ✔️
> * Nice animation 👏🏻
> * The JavaScript code is implemented following the best practices  👍🏻
> 
> Keep on coding, good job so far! 👏
> 
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> 
> 
> ## Required Changes ♻️
> * [ ]  This is the first project in which you should set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters in the project repository
>   Please open the [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) and make sure to follow all the steps in order to properly setup JS linters.
> 
> Cheers and Happy coding! 👏 👏 👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks so much for your remarks. I have a question, I would appreciate if you may answer it.

Do you mean that I need to configure my repo with eslint which is missing right now or is there anything else that I might be missing?

**Comment by ShoiraTa** [comment]
Hi, @HamzaAnwar1998. First let me explain that there are different settings of eslint depending on files that linters has to check: 
Screenshot 2022-02-28 at 23 23 45
As you can see there are different links for [html&css](https://github.com/microverseinc/linters-config/blob/master/html-css) and [html&css + javascript](https://github.com/microverseinc/linters-config/blob/master/html-css-js). So far you have been setting up linters only for HTML&CSS, from now on you should open the link with HTML,CSS and JavaScript. 

Accordingly, when you start ruby, you will have to setup linters for ruby etc. Hope my explanation was clear 🤗 . If you still have questions, leave comments or reach out in Slack. 
Link to linters config:  https://github.com/microverseinc/linters-config

**Review by micheaol — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hi @HamzaAnwar1998 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

well-1

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
